import 'package:equatable/equatable.dart';

/// Represents a complete travel itinerary for a group or individual.
///
/// An itinerary is the core entity in Kumo, containing all trip details:
/// destinations, dates, activities, accommodations, and expense tracking.
///
/// **Lifecycle:** draft → active → completed → archived
class TravelItinerary extends Equatable {
  /// Constructor for creating a new [TravelItinerary].
  ///
  /// @param id Unique identifier (generated by backend if omitted)
  /// @param title The name of the trip (required, non-empty)
  /// @param description Optional trip description
  /// @param startDate When the trip begins (required)
  /// @param endDate When the trip ends (required)
  /// @param ownerId UUID of the owner (required)
  /// @param members Initial group members (can be empty list)
  /// @param items Initial itinerary items (can be empty list)
  /// @param totalBudget Total trip budget (required, non-negative)
  /// @param currencyCode ISO currency code (required, valid ISO 4217)
  /// @param expenseSummary Expense breakdown (auto-calculated)
  /// @param createdAt Creation timestamp (set by backend)
  /// @param updatedAt Last modification timestamp (set by backend)
  /// @param status Initial status (default: draft)
  ///
  /// @throws [ArgumentError] if title is empty
  /// @throws [ArgumentError] if startDate is after endDate
  /// @throws [ArgumentError] if totalBudget is negative
  /// @throws [FormatException] if currencyCode is invalid
  ///
  /// Example:
  /// ```dart
  /// final itinerary = TravelItinerary(
  ///   id: '550e8400-e29b-41d4-a716-446655440000',
  ///   title: 'Tokyo Summer 2026',
  ///   description: 'An exciting week in Tokyo',
  ///   startDate: DateTime(2026, 6, 10),
  ///   endDate: DateTime(2026, 6, 17),
  ///   ownerId: 'user_alice',
  ///   totalBudget: 5000.00,
  ///   currencyCode: 'USD',
  ///   members: [
  ///     GroupMember(userId: 'user_alice', userName: 'Alice', role: GroupMemberRole.owner),
  ///     GroupMember(userId: 'user_bob', userName: 'Bob', role: GroupMemberRole.editor),
  ///   ],
  ///   items: [],
  ///   expenseSummary: ExpenseSummary(...),
  ///   createdAt: DateTime.now(),
  ///   updatedAt: DateTime.now(),
  /// );
  /// ```
  const TravelItinerary({
    required this.id,
    required this.title,
    required this.ownerId,
    required this.startDate,
    required this.endDate,
    required this.totalBudget,
    required this.currencyCode,
    required this.members,
    required this.items,
    required this.expenseSummary,
    required this.createdAt,
    required this.updatedAt,
    this.description,
    this.status = ItineraryStatusEnum.draft,
  });

  /// Unique identifier for this itinerary (UUID format).
  ///
  /// Generated by backend on creation. Immutable.
  /// @example "550e8400-e29b-41d4-a716-446655440000"
  final String id;

  /// Title/name of the trip.
  ///
  /// Examples: "Tokyo Summer 2026", "Paris Honeymoon", "Family Thailand Trip"
  /// Constraints: 1-255 characters, non-empty, unique per user (soft constraint)
  final String title;

  /// Brief description of the trip's purpose and highlights.
  ///
  /// Optional field for providing additional context.
  /// Constraints: 0-2000 characters
  /// Example: "A week exploring Tokyo temples, museums, and nightlife"
  final String? description;

  /// UUID of the user who created/owns this itinerary.
  ///
  /// The owner can transfer ownership to another group member.
  /// Immutable after creation.
  final String ownerId;

  /// UTC date when the trip starts.
  ///
  /// Constraints:
  /// - Must be after [createdAt]
  /// - Typically in the future (past trips allowed for historical records)
  /// - Cannot be more than 1 year in the future (configurable)
  final DateTime startDate;

  /// UTC date when the trip ends.
  ///
  /// Constraints:
  /// - Must be at or after [startDate]
  /// - Cannot exceed 365 days after startDate
  final DateTime endDate;

  /// Total trip budget in the specified currency.
  ///
  /// Sum of all expenses should not exceed this value.
  /// Constraints: 0.01 - 999,999.99
  /// @example 5000.00 (in USD)
  final double totalBudget;

  /// ISO 4217 currency code for all amounts in this itinerary.
  ///
  /// Examples: "USD", "JPY", "EUR", "GBP"
  /// Immutable after creation. All amounts are stored in this currency.
  /// Conversion happens client-side only; backend always uses same currency.
  final String currencyCode;

  /// List of group members invited to this itinerary.
  ///
  /// Each member has a role (viewer, editor, owner) and permissions.
  /// Owner can modify members list.
  /// @see [GroupMember]
  final List<GroupMember> members;

  /// Ordered list of daily activities and bookings.
  ///
  /// Sorted chronologically by [ItineraryItem.startTime].
  /// Each item can be an activity, accommodation, flight, etc.
  /// Max 1000 items per itinerary (soft constraint).
  final List<ItineraryItem> items;

  /// Summary of expenses split among group members.
  ///
  /// Updated in real-time as new expenses are added/removed.
  /// Recalculated whenever expense list changes.
  /// @see [ExpenseSummary]
  final ExpenseSummary expenseSummary;

  /// Timestamp when this itinerary was created (UTC).
  ///
  /// Set automatically by backend; not user-modifiable.
  /// Immutable. Used for sorting and filtering.
  final DateTime createdAt;

  /// Timestamp when this itinerary was last modified (UTC).
  ///
  /// Updated automatically whenever any field changes.
  /// Used to detect stale caches and enable optimistic conflict resolution.
  final DateTime updatedAt;

  /// Status of the itinerary.
  ///
  /// - `draft`: In preparation, not yet shared
  /// - `active`: Trip is happening or upcoming
  /// - `completed`: Trip has finished
  /// - `archived`: Moved to archive by user
  /// @see [ItineraryStatusEnum]
  final ItineraryStatusEnum status;

  /// Creates a copy of this [TravelItinerary] with optionally replaced fields.
  ///
  /// Useful for immutable updates without modifying original.
  /// Unspecified fields retain their original values.
  ///
  /// @returns A new [TravelItinerary] instance with updated fields
  ///
  /// Example:
  /// ```dart
  /// final updated = itinerary.copyWith(
  ///   title: 'Tokyo Summer 2026 - Updated',
  ///   status: ItineraryStatusEnum.active,
  /// );
  /// ```
  TravelItinerary copyWith({
    String? id,
    String? title,
    String? description,
    String? ownerId,
    DateTime? startDate,
    DateTime? endDate,
    double? totalBudget,
    String? currencyCode,
    List<GroupMember>? members,
    List<ItineraryItem>? items,
    ExpenseSummary? expenseSummary,
    DateTime? createdAt,
    DateTime? updatedAt,
    ItineraryStatusEnum? status,
  }) => TravelItinerary(
    id: id ?? this.id,
    title: title ?? this.title,
    description: description ?? this.description,
    ownerId: ownerId ?? this.ownerId,
    startDate: startDate ?? this.startDate,
    endDate: endDate ?? this.endDate,
    totalBudget: totalBudget ?? this.totalBudget,
    currencyCode: currencyCode ?? this.currencyCode,
    members: members ?? this.members,
    items: items ?? this.items,
    expenseSummary: expenseSummary ?? this.expenseSummary,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
    status: status ?? this.status,
  );

  @override
  List<Object?> get props => [
    id,
    title,
    description,
    ownerId,
    startDate,
    endDate,
    totalBudget,
    currencyCode,
    members,
    items,
    expenseSummary,
    createdAt,
    updatedAt,
    status,
  ];
}

/// Enum representing the status of an itinerary.
enum ItineraryStatusEnum {
  /// Itinerary is being drafted, not yet shared.
  draft,

  /// Itinerary is active (trip is upcoming or ongoing).
  active,

  /// Trip has finished.
  completed,

  /// Itinerary has been archived by the user.
  archived,
}

/// Represents a member in a group itinerary.
///
/// Contains user reference and role/permission information.
class GroupMember extends Equatable {
  const GroupMember({
    required this.userId,
    required this.userName,
    required this.role,
    required this.joinedAt,
  });

  /// UUID of the user.
  final String userId;

  /// Display name of the user (for quick reference).
  final String userName;

  /// Role within the group (viewer, editor, owner).
  final GroupMemberRole role;

  /// Timestamp when this user was added to the group.
  final DateTime joinedAt;

  @override
  List<Object> get props => [userId, userName, role, joinedAt];
}

/// Enum for group member roles with permission hierarchy.
enum GroupMemberRole {
  /// Can only view the itinerary (read-only).
  viewer,

  /// Can view and edit the itinerary (read-write).
  editor,

  /// Full ownership and control (all permissions).
  owner,
}

/// Summary of expenses for an itinerary.
///
/// Automatically calculated from expense list.
/// Used for quick access to key financial metrics.
class ExpenseSummary extends Equatable {
  const ExpenseSummary({
    required this.totalSpent,
    required this.spentByCategory,
    required this.memberBalances,
  });

  /// Total amount spent so far.
  final double totalSpent;

  /// Breakdown of spending by category.
  /// Keys: category names (e.g., "flights", "hotels", "food")
  /// Values: amount spent in that category
  final Map<String, double> spentByCategory;

  /// Individual balances for each group member.
  /// Key: user ID
  /// Value: balance (positive = owed to user, negative = owes others)
  final Map<String, double> memberBalances;

  @override
  List<Object> get props => [totalSpent, spentByCategory, memberBalances];
}

/// Represents a single item in an itinerary (activity, accommodation, etc.).
///
/// Each item is scheduled at a specific time and can have optional details.
class ItineraryItem extends Equatable {
  const ItineraryItem({
    required this.id,
    required this.itemType,
    required this.title,
    required this.startTime,
    this.endTime,
    this.location,
    this.latitude,
    this.longitude,
  });

  /// Unique identifier for this item (UUID format).
  final String id;

  /// Type of item categorizing the activity.
  /// Examples: "activity", "flight", "hotel", "restaurant", "transport"
  final String itemType;

  /// Title/name of the activity or booking.
  /// Example: "Senso-ji Temple Visit", "Tokyo to Osaka Flight"
  final String title;

  /// When the item starts (UTC).
  final DateTime startTime;

  /// When the item ends (UTC, optional).
  ///
  /// If null, duration is unknown or item doesn't have an end time.
  final DateTime? endTime;

  /// Optional location information.
  /// Example: "Asakusa, Tokyo" or full address
  final String? location;

  /// Latitude for map display (optional).
  final double? latitude;

  /// Longitude for map display (optional).
  final double? longitude;

  @override
  List<Object?> get props => [
    id,
    itemType,
    title,
    startTime,
    endTime,
    location,
    latitude,
    longitude,
  ];
}
