import 'package:equatable/equatable.dart';

/// Represents an authenticated user in the Kumo system.
///
/// Domain entity modelling user information after successful authentication.
/// Contains profile data and authentication status.
class User extends Equatable {
  /// Constructor for creating a [User] instance.
  ///
  /// @param id User's unique identifier (UUID)
  /// @param email User's email address
  /// @param displayName Optional display name
  /// @param avatarUrl Optional profile picture URL
  /// @param createdAt Account creation timestamp
  /// @param lastSignInAt Last login timestamp
  /// @param emailVerified Whether email is verified
  /// @param phoneNumber Optional phone number
  /// @param mfaEnabled Whether MFA is enabled
  ///
  /// Example:
  /// ```dart
  /// final user = User(
  ///   id: '550e8400-e29b-41d4-a716-446655440000',
  ///   email: 'user@example.com',
  ///   displayName: 'John Doe',
  ///   createdAt: DateTime.now(),
  ///   emailVerified: true,
  ///   mfaEnabled: false,
  /// );
  /// ```
  const User({
    required this.id,
    required this.email,
    required this.createdAt,
    this.displayName,
    this.avatarUrl,
    this.lastSignInAt,
    this.emailVerified = false,
    this.phoneNumber,
    this.mfaEnabled = false,
  });

  /// Unique identifier (UUID) for the user.
  ///
  /// Generated by Supabase Auth. Used as foreign key in other tables.
  /// @example "550e8400-e29b-41d4-a716-446655440000"
  final String id;

  /// User's email address (unique).
  ///
  /// Used for login and password reset.
  /// Must be a valid email format (validated during signup).
  final String email;

  /// User's display name.
  ///
  /// Optional field. Can be updated by user in profile settings.
  /// Constraints: 1-100 characters
  final String? displayName;

  /// URL to user's profile picture/avatar.
  ///
  /// Optional. Stored in Supabase Storage bucket.
  /// @example "https://project.supabase.co/storage/v1/object/public/avatars/user_id.jpg"
  final String? avatarUrl;

  /// Timestamp when the user account was created (UTC).
  ///
  /// Set automatically by Supabase Auth. Immutable.
  final DateTime createdAt;

  /// Timestamp when user last logged in (UTC).
  ///
  /// Updated automatically by Supabase Auth.
  /// Useful for activity tracking and user engagement metrics.
  final DateTime? lastSignInAt;

  /// Whether the user has verified their email address.
  ///
  /// Initially `false`. User must click verification link in email to set to `true`.
  /// Email verification may be required for certain features.
  final bool emailVerified;

  /// User's phone number (if provided).
  ///
  /// Optional. Used for optional phone-based MFA or contact.
  /// Stored in international format.
  final String? phoneNumber;

  /// Whether the user has set up MFA (multi-factor authentication).
  ///
  /// If `true`, additional verification (TOTP or SMS) required for login.
  final bool mfaEnabled;

  /// Creates a copy of this [User] with optionally replaced fields.
  ///
  /// Useful for immutable updates. All unspecified fields retain their values.
  ///
  /// @returns A new [User] instance with updated fields
  ///
  /// Example:
  /// ```dart
  /// final updatedUser = user.copyWith(displayName: 'Jane Doe');
  /// ```
  User copyWith({
    String? id,
    String? email,
    String? displayName,
    String? avatarUrl,
    DateTime? createdAt,
    DateTime? lastSignInAt,
    bool? emailVerified,
    String? phoneNumber,
    bool? mfaEnabled,
  }) => User(
    id: id ?? this.id,
    email: email ?? this.email,
    displayName: displayName ?? this.displayName,
    avatarUrl: avatarUrl ?? this.avatarUrl,
    createdAt: createdAt ?? this.createdAt,
    lastSignInAt: lastSignInAt ?? this.lastSignInAt,
    emailVerified: emailVerified ?? this.emailVerified,
    phoneNumber: phoneNumber ?? this.phoneNumber,
    mfaEnabled: mfaEnabled ?? this.mfaEnabled,
  );

  @override
  List<Object?> get props => [
    id,
    email,
    displayName,
    avatarUrl,
    createdAt,
    lastSignInAt,
    emailVerified,
    phoneNumber,
    mfaEnabled,
  ];
}
