class LookupEntry {
  const LookupEntry(this.code, this.name);
  final String code;
  final String name;
}

// ── Countries (ISO 3166-1 alpha-2) ───────────────────────────────────────────

const List<LookupEntry> kCountries = [
  LookupEntry('AD', 'Andorra'),
  LookupEntry('AE', 'United Arab Emirates'),
  LookupEntry('AF', 'Afghanistan'),
  LookupEntry('AG', 'Antigua and Barbuda'),
  LookupEntry('AL', 'Albania'),
  LookupEntry('AM', 'Armenia'),
  LookupEntry('AO', 'Angola'),
  LookupEntry('AR', 'Argentina'),
  LookupEntry('AT', 'Austria'),
  LookupEntry('AU', 'Australia'),
  LookupEntry('AZ', 'Azerbaijan'),
  LookupEntry('BA', 'Bosnia and Herzegovina'),
  LookupEntry('BB', 'Barbados'),
  LookupEntry('BD', 'Bangladesh'),
  LookupEntry('BE', 'Belgium'),
  LookupEntry('BF', 'Burkina Faso'),
  LookupEntry('BG', 'Bulgaria'),
  LookupEntry('BH', 'Bahrain'),
  LookupEntry('BI', 'Burundi'),
  LookupEntry('BJ', 'Benin'),
  LookupEntry('BN', 'Brunei'),
  LookupEntry('BO', 'Bolivia'),
  LookupEntry('BR', 'Brazil'),
  LookupEntry('BS', 'Bahamas'),
  LookupEntry('BT', 'Bhutan'),
  LookupEntry('BW', 'Botswana'),
  LookupEntry('BY', 'Belarus'),
  LookupEntry('BZ', 'Belize'),
  LookupEntry('CA', 'Canada'),
  LookupEntry('CD', 'DR Congo'),
  LookupEntry('CF', 'Central African Republic'),
  LookupEntry('CG', 'Republic of the Congo'),
  LookupEntry('CH', 'Switzerland'),
  LookupEntry('CI', "Côte d'Ivoire"),
  LookupEntry('CL', 'Chile'),
  LookupEntry('CM', 'Cameroon'),
  LookupEntry('CN', 'China'),
  LookupEntry('CO', 'Colombia'),
  LookupEntry('CR', 'Costa Rica'),
  LookupEntry('CU', 'Cuba'),
  LookupEntry('CV', 'Cape Verde'),
  LookupEntry('CY', 'Cyprus'),
  LookupEntry('CZ', 'Czech Republic'),
  LookupEntry('DE', 'Germany'),
  LookupEntry('DJ', 'Djibouti'),
  LookupEntry('DK', 'Denmark'),
  LookupEntry('DM', 'Dominica'),
  LookupEntry('DO', 'Dominican Republic'),
  LookupEntry('DZ', 'Algeria'),
  LookupEntry('EC', 'Ecuador'),
  LookupEntry('EE', 'Estonia'),
  LookupEntry('EG', 'Egypt'),
  LookupEntry('ER', 'Eritrea'),
  LookupEntry('ES', 'Spain'),
  LookupEntry('ET', 'Ethiopia'),
  LookupEntry('FI', 'Finland'),
  LookupEntry('FJ', 'Fiji'),
  LookupEntry('FR', 'France'),
  LookupEntry('GA', 'Gabon'),
  LookupEntry('GB', 'United Kingdom'),
  LookupEntry('GD', 'Grenada'),
  LookupEntry('GE', 'Georgia'),
  LookupEntry('GH', 'Ghana'),
  LookupEntry('GM', 'Gambia'),
  LookupEntry('GN', 'Guinea'),
  LookupEntry('GQ', 'Equatorial Guinea'),
  LookupEntry('GR', 'Greece'),
  LookupEntry('GT', 'Guatemala'),
  LookupEntry('GW', 'Guinea-Bissau'),
  LookupEntry('GY', 'Guyana'),
  LookupEntry('HN', 'Honduras'),
  LookupEntry('HR', 'Croatia'),
  LookupEntry('HT', 'Haiti'),
  LookupEntry('HU', 'Hungary'),
  LookupEntry('ID', 'Indonesia'),
  LookupEntry('IE', 'Ireland'),
  LookupEntry('IL', 'Israel'),
  LookupEntry('IN', 'India'),
  LookupEntry('IQ', 'Iraq'),
  LookupEntry('IR', 'Iran'),
  LookupEntry('IS', 'Iceland'),
  LookupEntry('IT', 'Italy'),
  LookupEntry('JM', 'Jamaica'),
  LookupEntry('JO', 'Jordan'),
  LookupEntry('JP', 'Japan'),
  LookupEntry('KE', 'Kenya'),
  LookupEntry('KG', 'Kyrgyzstan'),
  LookupEntry('KH', 'Cambodia'),
  LookupEntry('KI', 'Kiribati'),
  LookupEntry('KM', 'Comoros'),
  LookupEntry('KN', 'Saint Kitts and Nevis'),
  LookupEntry('KP', 'North Korea'),
  LookupEntry('KR', 'South Korea'),
  LookupEntry('KW', 'Kuwait'),
  LookupEntry('KZ', 'Kazakhstan'),
  LookupEntry('LA', 'Laos'),
  LookupEntry('LB', 'Lebanon'),
  LookupEntry('LC', 'Saint Lucia'),
  LookupEntry('LI', 'Liechtenstein'),
  LookupEntry('LK', 'Sri Lanka'),
  LookupEntry('LR', 'Liberia'),
  LookupEntry('LS', 'Lesotho'),
  LookupEntry('LT', 'Lithuania'),
  LookupEntry('LU', 'Luxembourg'),
  LookupEntry('LV', 'Latvia'),
  LookupEntry('LY', 'Libya'),
  LookupEntry('MA', 'Morocco'),
  LookupEntry('MC', 'Monaco'),
  LookupEntry('MD', 'Moldova'),
  LookupEntry('ME', 'Montenegro'),
  LookupEntry('MG', 'Madagascar'),
  LookupEntry('MK', 'North Macedonia'),
  LookupEntry('ML', 'Mali'),
  LookupEntry('MM', 'Myanmar'),
  LookupEntry('MN', 'Mongolia'),
  LookupEntry('MR', 'Mauritania'),
  LookupEntry('MT', 'Malta'),
  LookupEntry('MU', 'Mauritius'),
  LookupEntry('MV', 'Maldives'),
  LookupEntry('MW', 'Malawi'),
  LookupEntry('MX', 'Mexico'),
  LookupEntry('MY', 'Malaysia'),
  LookupEntry('MZ', 'Mozambique'),
  LookupEntry('NA', 'Namibia'),
  LookupEntry('NE', 'Niger'),
  LookupEntry('NG', 'Nigeria'),
  LookupEntry('NI', 'Nicaragua'),
  LookupEntry('NL', 'Netherlands'),
  LookupEntry('NO', 'Norway'),
  LookupEntry('NP', 'Nepal'),
  LookupEntry('NR', 'Nauru'),
  LookupEntry('NZ', 'New Zealand'),
  LookupEntry('OM', 'Oman'),
  LookupEntry('PA', 'Panama'),
  LookupEntry('PE', 'Peru'),
  LookupEntry('PG', 'Papua New Guinea'),
  LookupEntry('PH', 'Philippines'),
  LookupEntry('PK', 'Pakistan'),
  LookupEntry('PL', 'Poland'),
  LookupEntry('PT', 'Portugal'),
  LookupEntry('PW', 'Palau'),
  LookupEntry('PY', 'Paraguay'),
  LookupEntry('QA', 'Qatar'),
  LookupEntry('RO', 'Romania'),
  LookupEntry('RS', 'Serbia'),
  LookupEntry('RU', 'Russia'),
  LookupEntry('RW', 'Rwanda'),
  LookupEntry('SA', 'Saudi Arabia'),
  LookupEntry('SB', 'Solomon Islands'),
  LookupEntry('SC', 'Seychelles'),
  LookupEntry('SD', 'Sudan'),
  LookupEntry('SE', 'Sweden'),
  LookupEntry('SG', 'Singapore'),
  LookupEntry('SI', 'Slovenia'),
  LookupEntry('SK', 'Slovakia'),
  LookupEntry('SL', 'Sierra Leone'),
  LookupEntry('SM', 'San Marino'),
  LookupEntry('SN', 'Senegal'),
  LookupEntry('SO', 'Somalia'),
  LookupEntry('SR', 'Suriname'),
  LookupEntry('SS', 'South Sudan'),
  LookupEntry('ST', 'São Tomé and Príncipe'),
  LookupEntry('SV', 'El Salvador'),
  LookupEntry('SY', 'Syria'),
  LookupEntry('SZ', 'Eswatini'),
  LookupEntry('TD', 'Chad'),
  LookupEntry('TG', 'Togo'),
  LookupEntry('TH', 'Thailand'),
  LookupEntry('TJ', 'Tajikistan'),
  LookupEntry('TL', 'Timor-Leste'),
  LookupEntry('TM', 'Turkmenistan'),
  LookupEntry('TN', 'Tunisia'),
  LookupEntry('TO', 'Tonga'),
  LookupEntry('TR', 'Turkey'),
  LookupEntry('TT', 'Trinidad and Tobago'),
  LookupEntry('TV', 'Tuvalu'),
  LookupEntry('TZ', 'Tanzania'),
  LookupEntry('UA', 'Ukraine'),
  LookupEntry('UG', 'Uganda'),
  LookupEntry('US', 'United States'),
  LookupEntry('UY', 'Uruguay'),
  LookupEntry('UZ', 'Uzbekistan'),
  LookupEntry('VA', 'Vatican City'),
  LookupEntry('VC', 'Saint Vincent and the Grenadines'),
  LookupEntry('VE', 'Venezuela'),
  LookupEntry('VN', 'Vietnam'),
  LookupEntry('VU', 'Vanuatu'),
  LookupEntry('WS', 'Samoa'),
  LookupEntry('YE', 'Yemen'),
  LookupEntry('ZA', 'South Africa'),
  LookupEntry('ZM', 'Zambia'),
  LookupEntry('ZW', 'Zimbabwe'),
];

// ── Timezones (IANA) ─────────────────────────────────────────────────────────
// code = IANA zone identifier; name = human-readable label

const List<LookupEntry> kTimezones = [
  LookupEntry('Pacific/Midway',      'Midway Island (UTC−11)'),
  LookupEntry('Pacific/Honolulu',    'Hawaii (UTC−10)'),
  LookupEntry('America/Anchorage',   'Alaska (UTC−9)'),
  LookupEntry('America/Los_Angeles', 'Pacific Time – US & Canada (UTC−8)'),
  LookupEntry('America/Tijuana',     'Tijuana, Baja California (UTC−8)'),
  LookupEntry('America/Denver',      'Mountain Time – US & Canada (UTC−7)'),
  LookupEntry('America/Phoenix',     'Arizona (UTC−7)'),
  LookupEntry('America/Chicago',     'Central Time – US & Canada (UTC−6)'),
  LookupEntry('America/Mexico_City', 'Mexico City (UTC−6)'),
  LookupEntry('America/Regina',      'Saskatchewan (UTC−6)'),
  LookupEntry('America/New_York',    'Eastern Time – US & Canada (UTC−5)'),
  LookupEntry('America/Bogota',      'Bogota, Lima, Quito (UTC−5)'),
  LookupEntry('America/Toronto',     'Toronto (UTC−5)'),
  LookupEntry('America/Indiana/Indianapolis', 'Indiana (East) (UTC−5)'),
  LookupEntry('America/Caracas',     'Caracas (UTC−4)'),
  LookupEntry('America/Halifax',     'Atlantic Time – Canada (UTC−4)'),
  LookupEntry('America/Manaus',      'Manaus (UTC−4)'),
  LookupEntry('America/Santiago',    'Santiago (UTC−4)'),
  LookupEntry('America/St_Johns',    'Newfoundland (UTC−3:30)'),
  LookupEntry('America/Sao_Paulo',   'Brasilia (UTC−3)'),
  LookupEntry('America/Argentina/Buenos_Aires', 'Buenos Aires (UTC−3)'),
  LookupEntry('America/Godthab',     'Greenland (UTC−3)'),
  LookupEntry('Atlantic/South_Georgia', 'Mid-Atlantic (UTC−2)'),
  LookupEntry('Atlantic/Azores',     'Azores (UTC−1)'),
  LookupEntry('Atlantic/Cape_Verde', 'Cape Verde Islands (UTC−1)'),
  LookupEntry('UTC',                 'UTC / Coordinated Universal Time'),
  LookupEntry('Europe/London',       'London, Edinburgh, Lisbon (UTC+0)'),
  LookupEntry('Atlantic/Reykjavik',  'Reykjavik (UTC+0)'),
  LookupEntry('Africa/Casablanca',   'Casablanca, Monrovia (UTC+0)'),
  LookupEntry('Europe/Paris',        'Amsterdam, Berlin, Paris, Rome (UTC+1)'),
  LookupEntry('Europe/Warsaw',       'Warsaw, Prague, Budapest (UTC+1)'),
  LookupEntry('Africa/Lagos',        'West Central Africa (UTC+1)'),
  LookupEntry('Europe/Athens',       'Athens, Bucharest (UTC+2)'),
  LookupEntry('Africa/Cairo',        'Cairo (UTC+2)'),
  LookupEntry('Africa/Johannesburg', 'Harare, Pretoria (UTC+2)'),
  LookupEntry('Asia/Jerusalem',      'Jerusalem (UTC+2)'),
  LookupEntry('Europe/Helsinki',     'Helsinki, Kyiv, Riga, Tallinn (UTC+2)'),
  LookupEntry('Europe/Istanbul',     'Istanbul (UTC+3)'),
  LookupEntry('Asia/Baghdad',        'Baghdad (UTC+3)'),
  LookupEntry('Africa/Nairobi',      'Nairobi (UTC+3)'),
  LookupEntry('Europe/Moscow',       'Moscow, St. Petersburg (UTC+3)'),
  LookupEntry('Asia/Riyadh',         'Kuwait, Riyadh (UTC+3)'),
  LookupEntry('Asia/Tehran',         'Tehran (UTC+3:30)'),
  LookupEntry('Asia/Dubai',          'Abu Dhabi, Muscat (UTC+4)'),
  LookupEntry('Asia/Baku',           'Baku, Tbilisi, Yerevan (UTC+4)'),
  LookupEntry('Asia/Kabul',          'Kabul (UTC+4:30)'),
  LookupEntry('Asia/Tashkent',       'Islamabad, Karachi, Tashkent (UTC+5)'),
  LookupEntry('Asia/Kolkata',        'Chennai, Kolkata, Mumbai, New Delhi (UTC+5:30)'),
  LookupEntry('Asia/Kathmandu',      'Kathmandu (UTC+5:45)'),
  LookupEntry('Asia/Almaty',         'Almaty, Novosibirsk (UTC+6)'),
  LookupEntry('Asia/Dhaka',          'Dhaka (UTC+6)'),
  LookupEntry('Asia/Yangon',         'Yangon (UTC+6:30)'),
  LookupEntry('Asia/Bangkok',        'Bangkok, Hanoi, Jakarta (UTC+7)'),
  LookupEntry('Asia/Krasnoyarsk',    'Krasnoyarsk (UTC+7)'),
  LookupEntry('Asia/Shanghai',       'Beijing, Chongqing, Hong Kong, Urumqi (UTC+8)'),
  LookupEntry('Asia/Singapore',      'Kuala Lumpur, Singapore (UTC+8)'),
  LookupEntry('Asia/Taipei',         'Taipei (UTC+8)'),
  LookupEntry('Australia/Perth',     'Perth (UTC+8)'),
  LookupEntry('Asia/Irkutsk',        'Irkutsk (UTC+8)'),
  LookupEntry('Asia/Seoul',          'Seoul (UTC+9)'),
  LookupEntry('Asia/Tokyo',          'Osaka, Sapporo, Tokyo (UTC+9)'),
  LookupEntry('Asia/Yakutsk',        'Yakutsk (UTC+9)'),
  LookupEntry('Australia/Adelaide',  'Adelaide (UTC+9:30)'),
  LookupEntry('Australia/Darwin',    'Darwin (UTC+9:30)'),
  LookupEntry('Australia/Brisbane',  'Brisbane (UTC+10)'),
  LookupEntry('Australia/Sydney',    'Canberra, Melbourne, Sydney (UTC+10)'),
  LookupEntry('Pacific/Guam',        'Guam, Port Moresby (UTC+10)'),
  LookupEntry('Asia/Vladivostok',    'Vladivostok (UTC+10)'),
  LookupEntry('Australia/Hobart',    'Hobart (UTC+11)'),
  LookupEntry('Pacific/Noumea',      'Solomon Islands, New Caledonia (UTC+11)'),
  LookupEntry('Pacific/Auckland',    'Auckland, Wellington (UTC+12)'),
  LookupEntry('Pacific/Fiji',        'Fiji, Kamchatka, Marshall Islands (UTC+12)'),
  LookupEntry('Pacific/Tongatapu',   'Nuku\'alofa (UTC+13)'),
];

// ── Currencies (ISO 4217) ─────────────────────────────────────────────────────

const List<LookupEntry> kCurrencies = [
  LookupEntry('AED', 'UAE Dirham'),
  LookupEntry('ARS', 'Argentine Peso'),
  LookupEntry('AUD', 'Australian Dollar'),
  LookupEntry('BDT', 'Bangladeshi Taka'),
  LookupEntry('BGN', 'Bulgarian Lev'),
  LookupEntry('BRL', 'Brazilian Real'),
  LookupEntry('CAD', 'Canadian Dollar'),
  LookupEntry('CHF', 'Swiss Franc'),
  LookupEntry('CLP', 'Chilean Peso'),
  LookupEntry('CNY', 'Chinese Yuan'),
  LookupEntry('COP', 'Colombian Peso'),
  LookupEntry('CZK', 'Czech Koruna'),
  LookupEntry('DKK', 'Danish Krone'),
  LookupEntry('EGP', 'Egyptian Pound'),
  LookupEntry('EUR', 'Euro'),
  LookupEntry('GBP', 'British Pound Sterling'),
  LookupEntry('HKD', 'Hong Kong Dollar'),
  LookupEntry('HUF', 'Hungarian Forint'),
  LookupEntry('IDR', 'Indonesian Rupiah'),
  LookupEntry('ILS', 'Israeli New Shekel'),
  LookupEntry('INR', 'Indian Rupee'),
  LookupEntry('JPY', 'Japanese Yen'),
  LookupEntry('KRW', 'South Korean Won'),
  LookupEntry('KWD', 'Kuwaiti Dinar'),
  LookupEntry('LKR', 'Sri Lankan Rupee'),
  LookupEntry('MAD', 'Moroccan Dirham'),
  LookupEntry('MXN', 'Mexican Peso'),
  LookupEntry('MYR', 'Malaysian Ringgit'),
  LookupEntry('NOK', 'Norwegian Krone'),
  LookupEntry('NPR', 'Nepalese Rupee'),
  LookupEntry('NZD', 'New Zealand Dollar'),
  LookupEntry('PEN', 'Peruvian Sol'),
  LookupEntry('PHP', 'Philippine Peso'),
  LookupEntry('PKR', 'Pakistani Rupee'),
  LookupEntry('PLN', 'Polish Zloty'),
  LookupEntry('QAR', 'Qatari Riyal'),
  LookupEntry('RON', 'Romanian Leu'),
  LookupEntry('RUB', 'Russian Ruble'),
  LookupEntry('SAR', 'Saudi Riyal'),
  LookupEntry('SEK', 'Swedish Krona'),
  LookupEntry('SGD', 'Singapore Dollar'),
  LookupEntry('THB', 'Thai Baht'),
  LookupEntry('TRY', 'Turkish Lira'),
  LookupEntry('TWD', 'New Taiwan Dollar'),
  LookupEntry('UAH', 'Ukrainian Hryvnia'),
  LookupEntry('USD', 'US Dollar'),
  LookupEntry('VND', 'Vietnamese Dong'),
  LookupEntry('ZAR', 'South African Rand'),
];

// ── Languages (ISO 639-1) ────────────────────────────────────────────────────

const List<LookupEntry> kLanguages = [
  LookupEntry('af', 'Afrikaans'),
  LookupEntry('ar', 'Arabic'),
  LookupEntry('az', 'Azerbaijani'),
  LookupEntry('be', 'Belarusian'),
  LookupEntry('bg', 'Bulgarian'),
  LookupEntry('bn', 'Bengali'),
  LookupEntry('ca', 'Catalan'),
  LookupEntry('cs', 'Czech'),
  LookupEntry('cy', 'Welsh'),
  LookupEntry('da', 'Danish'),
  LookupEntry('de', 'German'),
  LookupEntry('el', 'Greek'),
  LookupEntry('en', 'English'),
  LookupEntry('es', 'Spanish'),
  LookupEntry('et', 'Estonian'),
  LookupEntry('eu', 'Basque'),
  LookupEntry('fa', 'Persian'),
  LookupEntry('fi', 'Finnish'),
  LookupEntry('fr', 'French'),
  LookupEntry('gl', 'Galician'),
  LookupEntry('gu', 'Gujarati'),
  LookupEntry('he', 'Hebrew'),
  LookupEntry('hi', 'Hindi'),
  LookupEntry('hr', 'Croatian'),
  LookupEntry('hu', 'Hungarian'),
  LookupEntry('hy', 'Armenian'),
  LookupEntry('id', 'Indonesian'),
  LookupEntry('is', 'Icelandic'),
  LookupEntry('it', 'Italian'),
  LookupEntry('ja', 'Japanese'),
  LookupEntry('ka', 'Georgian'),
  LookupEntry('kk', 'Kazakh'),
  LookupEntry('km', 'Khmer'),
  LookupEntry('kn', 'Kannada'),
  LookupEntry('ko', 'Korean'),
  LookupEntry('lt', 'Lithuanian'),
  LookupEntry('lv', 'Latvian'),
  LookupEntry('mk', 'Macedonian'),
  LookupEntry('ml', 'Malayalam'),
  LookupEntry('mn', 'Mongolian'),
  LookupEntry('mr', 'Marathi'),
  LookupEntry('ms', 'Malay'),
  LookupEntry('my', 'Burmese'),
  LookupEntry('ne', 'Nepali'),
  LookupEntry('nl', 'Dutch'),
  LookupEntry('no', 'Norwegian'),
  LookupEntry('pa', 'Punjabi'),
  LookupEntry('pl', 'Polish'),
  LookupEntry('pt', 'Portuguese'),
  LookupEntry('ro', 'Romanian'),
  LookupEntry('ru', 'Russian'),
  LookupEntry('si', 'Sinhala'),
  LookupEntry('sk', 'Slovak'),
  LookupEntry('sl', 'Slovenian'),
  LookupEntry('sq', 'Albanian'),
  LookupEntry('sr', 'Serbian'),
  LookupEntry('sv', 'Swedish'),
  LookupEntry('sw', 'Swahili'),
  LookupEntry('ta', 'Tamil'),
  LookupEntry('te', 'Telugu'),
  LookupEntry('th', 'Thai'),
  LookupEntry('tk', 'Turkmen'),
  LookupEntry('tr', 'Turkish'),
  LookupEntry('uk', 'Ukrainian'),
  LookupEntry('ur', 'Urdu'),
  LookupEntry('uz', 'Uzbek'),
  LookupEntry('vi', 'Vietnamese'),
  LookupEntry('zh', 'Chinese'),
  LookupEntry('zu', 'Zulu'),
];
